### ISSUE TITLE
`test.sh` must be executable.

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/noboty#24]
To be run as `./test.sh`, you'll need to use `chmod` to make the script executable. [Explanation](https://support.apple.com/guide/terminal/make-a-file-executable-apdd100908f-06b3-4e63-8a87-32e71241bab4/mac)

**Comment by ErikBoesen** [comment]
@JosephCarpenter Can you handle this? It's a one-command fix.

**Comment by irinade** [comment]
I do not understand the problem, after cloning the repo, I find that test.sh mode is executable for everybody.

**Comment by ErikBoesen** [comment]
@irinade This was fixed.
